# Generated by Django 4.1 on 2022-08-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
